package com.itwen.pojo;

public class Page {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_page.id
     *
     * @mbggenerated Fri Oct 14 13:07:14 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_page.username
     *
     * @mbggenerated Fri Oct 14 13:07:14 CST 2022
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_page.id
     *
     * @return the value of t_page.id
     *
     * @mbggenerated Fri Oct 14 13:07:14 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_page.id
     *
     * @param id the value for t_page.id
     *
     * @mbggenerated Fri Oct 14 13:07:14 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_page.username
     *
     * @return the value of t_page.username
     *
     * @mbggenerated Fri Oct 14 13:07:14 CST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_page.username
     *
     * @param username the value for t_page.username
     *
     * @mbggenerated Fri Oct 14 13:07:14 CST 2022
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    @Override
    public String toString() {
        return "Page{" +
                "id=" + id +
                ", username='" + username + '\'' +
                '}';
    }
}