package com.itwen.mapper;

import com.itwen.pojo.Page;
import com.itwen.pojo.PageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

public interface PageMapper {

    @ResultMap("pageResultMap")
    @Select("select * from t_page")
    List<Page> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_page
     *
     * @mbggenerated Fri Oct 14 13:07:14 CST 2022
     */
    int countByExample(PageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_page
     *
     * @mbggenerated Fri Oct 14 13:07:14 CST 2022
     */
    int deleteByExample(PageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_page
     *
     * @mbggenerated Fri Oct 14 13:07:14 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_page
     *
     * @mbggenerated Fri Oct 14 13:07:14 CST 2022
     */
    int insert(Page record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_page
     *
     * @mbggenerated Fri Oct 14 13:07:14 CST 2022
     */
    int insertSelective(Page record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_page
     *
     * @mbggenerated Fri Oct 14 13:07:14 CST 2022
     */
    List<Page> selectByExample(PageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_page
     *
     * @mbggenerated Fri Oct 14 13:07:14 CST 2022
     */
    Page selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_page
     *
     * @mbggenerated Fri Oct 14 13:07:14 CST 2022
     */
    int updateByExampleSelective(@Param("record") Page record, @Param("example") PageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_page
     *
     * @mbggenerated Fri Oct 14 13:07:14 CST 2022
     */
    int updateByExample(@Param("record") Page record, @Param("example") PageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_page
     *
     * @mbggenerated Fri Oct 14 13:07:14 CST 2022
     */
    int updateByPrimaryKeySelective(Page record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_page
     *
     * @mbggenerated Fri Oct 14 13:07:14 CST 2022
     */
    int updateByPrimaryKey(Page record);
}